-- MySQL Script generated by MySQL Workbench


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


CREATE SCHEMA IF NOT EXISTS `nirs` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `nirs` ;


-- -----------------------------------------------------
-- Table `nirs`.`node`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nirs`.`node` (
  `UUID` CHAR(36) NOT NULL,
  `parent` CHAR(36) NULL DEFAULT NULL,
  `project_name` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`UUID`),
  INDEX `parent_idx` (`parent` ASC) VISIBLE,
  CONSTRAINT `parent`
    FOREIGN KEY (`parent`)
    REFERENCES `nirs`.`node` (`UUID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nirs`.`generator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nirs`.`generator` (
  `id_generator` INT NOT NULL,
  `origin` CHAR(36) NULL DEFAULT NULL,
  `gen_type` INT NULL DEFAULT '0',
  `gen_value` VARCHAR(3000) NULL DEFAULT NULL,
  PRIMARY KEY (`id_generator`),
  INDEX `origin_idx` (`origin` ASC) VISIBLE,
  CONSTRAINT `origin`
    FOREIGN KEY (`origin`)
    REFERENCES `nirs`.`node` (`UUID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nirs`.`attribute`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nirs`.`attribute` (
  `id_attribute` INT NOT NULL,
  `UUID_defining` CHAR(36) NULL DEFAULT NULL,
  `attr_name` VARCHAR(500) NULL DEFAULT NULL,
  `id_generator` INT NULL DEFAULT NULL,
  `attr_flag` INT NULL DEFAULT NULL,
  `attr_scope` INT NULL DEFAULT '0',
  PRIMARY KEY (`id_attribute`),
  INDEX `node_UUID_idx` (`UUID_defining` ASC) VISIBLE,
  INDEX `id_generator_idx` (`id_generator` ASC) VISIBLE,
  CONSTRAINT `id_generator`
    FOREIGN KEY (`id_generator`)
    REFERENCES `nirs`.`generator` (`id_generator`),
  CONSTRAINT `UUID_defining`
    FOREIGN KEY (`UUID_defining`)
    REFERENCES `nirs`.`node` (`UUID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nirs`.`attr_value`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nirs`.`attr_value` (
  `id_attr_val` INT NOT NULL,
  `attr_value` VARCHAR(3000) NULL DEFAULT NULL,
  `attr_type` VARCHAR(300) NULL DEFAULT NULL,
  `id_attribute` INT NULL DEFAULT NULL,
  `UUID_using` CHAR(36) NULL DEFAULT NULL,
  PRIMARY KEY (`id_attr_val`),
  INDEX `UUID_counted_idx` (`UUID_using` ASC) VISIBLE,
  INDEX `id_attribute_idx` (`id_attribute` ASC) VISIBLE,
  CONSTRAINT `id_attribute`
    FOREIGN KEY (`id_attribute`)
    REFERENCES `nirs`.`attribute` (`id_attribute`),
  CONSTRAINT `UUID_using`
    FOREIGN KEY (`UUID_using`)
    REFERENCES `nirs`.`node` (`UUID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `nirs`.`value_provider`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nirs`.`value_provider` (
  `id_attr_val` INT NOT NULL,
  `raw_attr_value` VARCHAR(3000) NULL DEFAULT NULL,
  `raw_attr_type` VARCHAR(300) NULL DEFAULT NULL,
  `provider_type` VARCHAR(300) NULL DEFAULT '0',
  `settings` VARCHAR(3000) NULL DEFAULT NULL,
  PRIMARY KEY (`id_attr_val`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
